name = "cap-captcha-service"
main = "src/index.js"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespaces for storing challenge data
[[kv_namespaces]]
binding = "CAP_KV"
id = "0e3c8682116d48acaecb3276a6aaf4ff"


# Build configuration
[build]
command = ""
cwd = ""
watch_dir = "src"
